all: clean install

install:
	mkdir -p output build
	latexmk -pdf -bibtex -outdir=../build -cd src/thesis.tex
	mv build/thesis.pdf output

clean:
	rm -rf output build
	find . -iname "*~" -exec rm '{}' ';'
